CREATE TABLE Época(
    ano INT NOT NULL PRIMARY KEY
);

CREATE TABLE Equipa(
    idEquipa INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    género TEXT NOT NULL,
    idClube INT NOT NULL REFERENCES Clube(idClube)
);